export const API_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnZmUuY29tIiwidXNlcm5hbWUiOiJhZG1pbiIsInR5cGUiOiJBZG1pbiIsInBlcm1pc3Npb25zIjoiQURNSU5fREFTSEJPQVJELENBVEVHT1JZX0NSRUFURSxDQVRFR09SWV9GRVRDSCxDQVRFR09SWV9VUERBVEUsQ0FURUdPUllfREVMRVRFLENPTVBMSUFOQ0VfQ1JFQVRFLENPTVBMSUFOQ0VfRkVUQ0gsQ09NUExJQU5DRV9VUERBVEUsQ09NUExJQU5DRV9ERUxFVEUsQ1VTVE9NRVJfQ1JFQVRFLENVU1RPTUVSX0ZFVENILENVU1RPTUVSX1VQREFURSxDVVNUT01FUl9ERUxFVEUsQ1VTVE9NRVJfQ09OVFJBQ1RfQ1JFQVRFLENVU1RPTUVSX0NPTlRSQUNUX0ZFVENILENVU1RPTUVSX1NUQVRVU19NQVJLLENVU1RPTUVSX0RBU0hCT0FSRCxESVJFQ1RPUl9DUkVBVEUsRElSRUNUT1JfRkVUQ0gsRElSRUNUT1JfVVBEQVRFLERJUkVDVE9SX0RFTEVURSxESVJFQ1RPUl9TVEFUVVNfTUFSSyxHRkVfQ1JFQVRFLEdGRV9GRVRDSCxHRkVfVVBEQVRFLEdGRV9ERUxFVEUsR0ZFX0VOUVVFVUUsR0ZFX0RFUVVFVUUsR0ZFX1FVRVNUSU9OX0NSRUFURSxHRkVfUVVFU1RJT05fQU5TV0VSX0NSRUFURSxHRkVfU1RBVFVTX01BUkssR0ZFX1NDSEVEVUxFLElOVk9JQ0VfQ1JFQVRFLElOVk9JQ0VfQ1JFQVRFX0RJU0NPVU5ULElOVk9JQ0VfRkVUQ0gsTUFOVUZBQ1RVUkVSX0NSRUFURSxNQU5VRkFDVFVSRVJfRkVUQ0gsTUFOVUZBQ1RVUkVSX1VQREFURSxNQU5VRkFDVFVSRVJfREVMRVRFLFBBVElFTlRfQ1JFQVRFLFBBVElFTlRfRkVUQ0gsUEFUSUVOVF9VUERBVEUsUEFUSUVOVF9ERUxFVEUsUFJPVklERVJfQ1JFQVRFLFBST1ZJREVSX0ZFVENILFBST1ZJREVSX1VQREFURSxQUk9WSURFUl9ERUxFVEUsUFJPVklERVJfQ09OVFJBQ1RfQ1JFQVRFLFBST1ZJREVSX0NPTlRSQUNUX0ZFVENILFBST1ZJREVSX1NUQVRVU19NQVJLLFBST1ZJREVSX0RBU0hCT0FSRCxUUkVBVE1FTlRfQ1JFQVRFLFRSRUFUTUVOVF9GRVRDSCxUUkVBVE1FTlRfVVBEQVRFLFRSRUFUTUVOVF9ERUxFVEUsTE9DQVRJT05fQ1JFQVRFLExPQ0FUSU9OX0ZFVENILExPQ0FUSU9OX1VQREFURSxMT0NBVElPTl9ERUxFVEUsQ1VTVE9NRVJfVFJFQVRNRU5UU19TQVZFLENVU1RPTUVSX1RSRUFUTUVOVFNfRkVUQ0gsVFJFQVRNRU5UX1FVRVNUSU9OX1NBVkUsR0ZFX1JFVklFVyxDSEFOR0VfUEFTU1dPUkQsRElSRUNUT1JfTUVESUNBTF9GRVRDSCxDVVNUT01FUl9SRVNFTkQsQ1VTVE9NRVJfSU5WT0lDSU5HLElOVk9JQ0VfVVBEQVRFLEVORF9DQUxMLEdGRV9SRVBPUlQsR0ZFX0RBU0hCT0FSRCxQUk9WSURFUl9DT1VOVCxDVVNUT01FUl9DT1VOVCxQQVRJRU5UX09OTElORSxQUk9WSURFUl9QSU5HLFBST1ZJREVSX09OTElORSxQQVlNRU5UX0NSRUFURSxQQVlNRU5UX0ZFVENILEFEVkVSVElTRU1FTlRfQ1JFQVRFLEFEVkVSVElTRU1FTlRfRkVUQ0gsUVVFU1RJT05fQ1JFQVRFLFFVRVNUSU9OX0ZFVENILFFVRVNUSU9OX0ZFVENILFFVRVNUSU9OX1VQREFURSxRVUVTVElPTl9ERUxFVEUsR0ZFX0pPSU4sRU1BSUxfVVBEQVRFLFVTRVJfQUNUSVZFX1NUQVRVUyxHRUZfVVBEQVRFLFJFQ09SRElOR19TVEFSVCxPUEVSQVRJTkdfSE9VUl9DUkVBVEUsT1BFUkFUSU5HX0hPVVJfRkVUQ0gsSU5WT0lDRV9EQVNIQk9BUkQsQ1VTVE9NRVJfQVNTT0NfV0lUSF9NRURJQ0FMX0RJUkVDVE9SX0ZFVENILFBST1ZJREVSX0FERF9MT0NBVElPTixQUk9WSURFUl9GRVRDSF9MT0NBVElPTixNRURJQ0FMX0RJUkVDVE9SX0NVU1RPTUVSX0ZFVENILFBBVElFTlRfRkVUQ0hfQ1JFQVRFLENVU1RPTUVSX0ZFVENIX0xPQ0FUSU9OLEdGRV9TVEFUVVMsR0ZFX1NDSEVEVUxFX1JBVyxGRVRDSF9RVUVVRURfR0ZFX0ZJWCxUSUNLRVJfQ1JFQVRFLFRJQ0tFUl9GRVRDSCxET1NBR0VfQ1JFQVRFLERPU0FHRSIsImNsaWVudElkIjpudWxsLCJzZWNyZXRJZCI6bnVsbCwiY3JlYXRlZGJ5IjoxLCJjcmVhdGVkYXQiOiIyMDIyLTExLTI4VDIxOjI0OjM5LjAwMFoiLCJ1cGRhdGVkYnkiOjEsInVwZGF0ZWRhdCI6IjIwMjUtMDItMDhUMjA6Mjg6MjYuMDAwWiIsImlzQWN0aXZlIjp0cnVlLCJpYXQiOjE3NDM4ODcyNDYsImV4cCI6MTc0NjQ3OTI0Nn0.XmKxpuI6ITrvsVyqvP3JnDD5-3HhyGkZwvs5A1OADew';

export const API_BASE_URL = 'https://app.healthcoversonline.com/api';

const getAuthHeaders = () => ({
  'Authorization': `Bearer ${API_TOKEN}`,
});

export const fetchApi = async (endpoint: string, params?: Record<string, any>) => {
  // Handle pagination parameters specifically for /gfe endpoint
  if (endpoint.startsWith('/gfe') && !endpoint.includes('?')) {
    const { pageNo = 1, pageSize = 10, ...otherParams } = params || {};
    const queryParams = new URLSearchParams({
      pageNo: pageNo.toString(),
      pageSize: pageSize.toString(),
      ...otherParams
    });
    endpoint = `${endpoint}?${queryParams.toString()}`;
  }

  const response = await fetch(`${API_BASE_URL}${endpoint}`, {
    headers: getAuthHeaders(),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => null);
    // Handle "no gfe found" as a valid state
    if (response.status === 404 || errorData?.message === 'no gfe found') {
      return { payload: [], pagination: { totalRecords: 0, totalPages: 0, pageNo: 1, pageSize: 10 } };
    }
    throw new Error(errorData?.message || `API request failed: ${response.statusText}`);
  }

  const data = await response.json();
  
  // Validate pagination response for /gfe endpoint
  if (endpoint.startsWith('/gfe') && params?.pageNo) {
    if (data.pagination?.pageNo !== params.pageNo) {
      throw new Error('Pagination mismatch: Received page number does not match requested page');
    }
  }

  return data;
};